const TRY_LOGIN = 'TRY_LOGIN';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAILURE = 'LOGIN_FAILURE';

const REGISTER = 'REGISTER';
const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
const REGISTER_FAILURE = 'REGISTER_FAILURE';

const CHECK_MAIL_EXSISTANCE = 'CHECK_MAIL_EXISTANCE';
const CHECK_MAIL_SUCCESS = 'CHECK_MAIL_SUCCESS';
const CHECK_MAIL_FAILURE = 'CHECK_MAIL_FAILURE';

const LOG_OUT = 'LOG_OUT';

export const authConstants = {
  TRY_LOGIN,
  LOGIN_SUCCESS,
  LOGIN_FAILURE,
  REGISTER,
  REGISTER_SUCCESS,
  REGISTER_FAILURE,
  CHECK_MAIL_EXSISTANCE,
  CHECK_MAIL_SUCCESS,
  CHECK_MAIL_FAILURE,
  LOG_OUT
}